general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear la pantalla
    before_sleep_cmd = loginctl lock-session    # bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # encender la pantalla al despertar
}

# Bloquear la pantalla y pausar música tras 10 minutos de inactividad
listener {
    timeout = 600
    on-timeout = loginctl lock-session && playerctl pause
}

# Apagar monitores 1 minuto después del bloqueo (11 min total)
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on          # encender al detectar actividad
}

# Suspender tras 30 minutos de inactividad
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
