[main]
include=~/.config/foot/colors.ini
# Fuente recomendada para Powerlevel10k (ya instalada en tu sistema)
font=MesloLGS Nerd Font Mono:size=11

[cursor]
style=block
blink=yes

[colors]
# Esto asegura que los colores se vean bien con el tema de p10k
alpha=0.95
